### ISSUE TITLE
It is possible to highlight php code? 

### ISSUE THREAD

**Issue by ESPONI** [mukhortov/HESH-WordPress-Plugin#22]
We are going to include some **php snipets** inside posts and this could be great!

Awesome plugin BTW,
Best regards

**Comment by arniebradfo** [comment]
I'm not 100% sure what you mean.

Highlighting php in the editor wouldn't make sense because php entered into the post content won't run. 

Maybe you mean highlighting php code snippet on the front end? This plugin does not highlight anything on the frontend.

Maybe you mean in the theme and plugin editor pages? In that case, we support syntax highlighting on that page as of v2.0

Hopefully one of those answers your question.
