### ISSUE TITLE
Bugs found in v2.0-rc

### ISSUE THREAD

**Issue by mukhortov** [mukhortov/HESH-WordPress-Plugin#24]
### List of issues found in 2.0-rc from the latest "release" branch

 - [x] Large white space appears after the editor window has been resized - [GIF screencast](https://cloud.githubusercontent.com/assets/770278/24587385/196cbc22-17be-11e7-99a4-4ac4c2489f30.gif)
 - [x] Active line isn't highlighted. Also reported in #23
 - [x] When "full-height editor" mode is enabed the editor window shrinks into one line. [GIF screencast](https://cloud.githubusercontent.com/assets/770278/24587423/da95cf4c-17be-11e7-96ca-25bda7faee35.gif)
 - [x] "Add media" isn't working - [GIF screencast](https://cloud.githubusercontent.com/assets/770278/24587495/7d392194-17c0-11e7-96fa-91f27a5e0988.gif)
 - [x] Insert link feature ins't working - [GIF screencast](https://cloud.githubusercontent.com/assets/770278/24587530/0c9aa916-17c1-11e7-8b47-21a5a5fcf0f9.gif)
 - [x] Broken fullscreen mode with enabed "full-height editor" mode - [GIF screencast](https://cloud.githubusercontent.com/assets/770278/24587580/f125dd94-17c1-11e7-8c0b-1d76659c1c3e.gif)

**Comment by dries863** [comment]
Great to hear that you are still working on this plugin. I had to disable the old version since it wan't working anymore. The new one seems to be working better :-)

It seems like that none of the buttons (Italic, bold etc.) are working in text mode. Is that the same bug as "Insert link feature ins't working"?

**Comment by arniebradfo** [comment]
It sounds like you might be still using version 1.7.x. Did you download and install the most recent [release candidate](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/tag/v2.0.0-rc.7)? 

If you do please give us a bug report here and help make the product better

**Comment by arniebradfo** [comment]
Hey @mukhortov 

The bugs:
 - [ ] Large white space appears after the editor window has been resized 
  - I could not repro this but I think its fixed. Could you retest?
 - [x] Active line isn't highlighted. Also reported in
 - [ ] When "full-height editor" mode is enabled the editor window shrinks into one line.
  - I have no idea whats causing this, and I can't reproduce this. Could you give me repro steps, your browser, and your OS version?
 - [x] "Add media" isn't working.
 - [x] Insert link feature ins't working.
 - [x] Broken fullscreen mode with enabled "full-height editor" mode.
   - This is by design. The full screen button works like it used to when the 'enable distraction free' setting is not checked. When 'enable distraction free' is checked, the full-screen button enables the *distraction free* mode. This achieves parity with native WP text editor functionality and with the visual editor.

Thanks!

**Comment by mukhortov** [comment]
I've just tested it. Looks good now! I guess it's ready to go live. <br><br>

> - [ ] Large white space appears after the editor window has been resized 
>   - I could not repro this but I made some changes that might fix it. Could you retest?

I could not reproduce it anymore either. I guess your fix worked :) <br><br>


> - [x] Broken fullscreen mode with enabled "full-height editor" mode.
>   - This is by design. The full screen button works like it used to when the 'enable distraction free' setting is not checked. When 'enable distraction free' is checked, the full-screen button enables the *distraction free* mode. This achieves parity with native WP text editor functionality and with the visual editor.

What do you think about disabling ["full-height editor" mode ](https://cloud.githubusercontent.com/assets/770278/25781996/78994e20-334a-11e7-843d-f11ae99e0338.png) automatically once the plugin is activated or when the editor is switched to the text mode? This active "full-height editor" mode might add some weird UI glitches to the plugin.

Anyway, I guess this could be a separate issue and could go to one of the next releases.

**Comment by arniebradfo** [comment]
Yea, lets think about that later.
