### ISSUE TITLE
Maintain Tabbing as entered

### ISSUE THREAD

**Issue by sonyboy232** [mukhortov/HESH-WordPress-Plugin#83]
When tabbing code, some of it is maintained, while other times it is lost. For instance, if I have the following code tabbed the the way I want it:
```html
<ul>
    <li>
        <a>
            <img src="someimage.jpg" />
        </a>
        <a href="/link">Some Text</a>
    </li>
</ul>
```
After saving the page (or opening the menu), the tabbing changes as follows:
```html
<ul>
    <li>
        <a>
<img src="someimage.jpg" />
</a>
<a href="/link">Some Text</a></li>
</ul>
```
As you can see, the tabs are lost for the last 4 lines, and the ```</li>``` is moved off of it's own line and placed at the end of the ```<a>``` tag, all of which makes the code much harder to read.

**Comment by arniebradfo** [comment]
@sonyboy232 are you using Gutenberg or the Classic Editor?

**Comment by arniebradfo** [comment]
I believe this is something that the #35 auto-format feature would handle. Its caused by WordPress, not my plugin. Sorry.

If you're a regular user of this plugin, please consider taking a short [User Experience Survey](https://goo.gl/forms/xvaHgd7sZEbBbFAL2) to provide feedback that will help shape the new version 3.0.
